service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:PutBucketCORS
      Resource:
        - arn:aws:s3:::import-service-dev-serverlessdeploymentbucket-17pfto8u4npz6/*
        - arn:aws:s3:::import-service-dev-serverlessdeploymentbucket-17pfto8u4npz6
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:eu-west-1:854321213400:products-queue

functions:
  importProductsFile:
    handler: importProductsFile.handler
    events:
      - http:
          method: get
          path: import
          request:
            parameters:
              querystrings:
                name: true
    package:
      include:
        - node_modules/**
  importFileParser:
    handler: importFileParser.handler
    events:
      - s3:
          bucket: upload-bucket-volodymyr-vashchuk
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
    package:
      include:
        - node_modules/**